# Generated by Django 4.1.3 on 2023-05-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poste', '0002_alter_article_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=25),
        ),
    ]
